version: '3.5'

services:
  redis:
    image: 'redis:5.0.2-alpine'

  service-gateway:
    build: ./services/service-gateway
    ports:
      - "4000:4000"
    depends_on:
      - 'redis'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  worker-gather-information:
    build: ./services/worker-gather-information
    depends_on:
      - 'redis'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
